/**
 * @agentmesh/sdk — Solana adapter (scaffold).
 *
 * Mirrors the EVM SDK surface: same `mesh.identity.register`,
 * `mesh.marketplace.list`, `mesh.payment.fetchWithPayment`. Routes calls
 * through @solana/web3.js + Anchor IDL instead of viem.
 *
 * Status: scaffold. The Anchor IDL is regenerated by `anchor build`; until
 * the program is deployed to devnet/mainnet and the IDL synced, this
 * module exposes the public-API shape only. Wire it up after the program
 * deploys.
 *
 * Why ship the scaffold now:
 *   - Confirms the chain-agnostic SDK shape works for Solana
 *   - Lets the rest of the codebase reference `import { SolanaAgentMesh }`
 *   - One-day fill-in once Anchor IDL is generated
 */

export interface SolanaAgentMeshConfig {
  cluster: 'devnet' | 'mainnet-beta' | 'localhost';
  endpoint?: string;
  programId?: string;
  walletKey?: Uint8Array;
}

export interface SolanaRegistration {
  name: string;
  metadataURI: string;
  capabilities: string[]; // hashed via sha256, packed to 32 bytes
}

export interface SolanaListing {
  serviceURI: string;
  priceLamports: bigint;
}

const NOT_IMPLEMENTED = (feature: string) => () => {
  throw new Error(
    `[@agentmesh/sdk Solana adapter] ${feature} is scaffolded but not yet wired. Run \`anchor build\` then \`anchor deploy\` and regenerate the IDL.`,
  );
};

export class SolanaAgentMesh {
  readonly identity = {
    register: NOT_IMPLEMENTED('identity.register'),
    update: NOT_IMPLEMENTED('identity.update'),
    lookup: NOT_IMPLEMENTED('identity.lookup'),
  };
  readonly wallet = {
    create: NOT_IMPLEMENTED('wallet.create'),
    fund: NOT_IMPLEMENTED('wallet.fund'),
    getBalance: NOT_IMPLEMENTED('wallet.getBalance'),
  };
  readonly discovery = {
    findByCapability: NOT_IMPLEMENTED('discovery.findByCapability'),
  };
  readonly marketplace = {
    list: NOT_IMPLEMENTED('marketplace.list'),
    deactivate: NOT_IMPLEMENTED('marketplace.deactivate'),
    buy: NOT_IMPLEMENTED('marketplace.buy'),
    complete: NOT_IMPLEMENTED('marketplace.complete'),
    refund: NOT_IMPLEMENTED('marketplace.refund'),
  };
  readonly payment = {
    fetchWithPayment: NOT_IMPLEMENTED('payment.fetchWithPayment'),
  };
  readonly reputation = {
    get: NOT_IMPLEMENTED('reputation.get'),
  };

  constructor(public readonly config: SolanaAgentMeshConfig) {}

  static async create(config: SolanaAgentMeshConfig): Promise<SolanaAgentMesh> {
    return new SolanaAgentMesh(config);
  }

  /// Translate a capability string to the 32-byte hash used as a PDA seed
  /// component. We use sha256(string) on Solana (not keccak256 like EVM)
  /// because sha256 is cheaper in BPF — same string maps to a different
  /// hash on each chain, but downstream the SDK normalises.
  static async capabilityHash(capability: string): Promise<Uint8Array> {
    const enc = new TextEncoder().encode(capability);
    const buf = await crypto.subtle.digest('SHA-256', enc);
    return new Uint8Array(buf);
  }
}
